after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
cache:
  directories:
  - $HOME/.m2
  - $HOME/android-sdk-linux
git:
  depth: 10
install: mvn -T 2 -Ptravis -DskipTests=true -B -V install
language: java
matrix:
  include:
  - env: JACOCO=-Pjacoco
    jdk: openjdk7
  - before_install: if [ ! -d $HOME/android-sdk-linux/platforms ]; then curl -s https://storage.googleapis.com/zxing-build/android-sdk-linux.tar.bz2 | bunzip2 | tar xf - -C $HOME; else ls -l $HOME/android-sdk-linux; fi
    env: ANDROID_HOME=$HOME/android-sdk-linux
    jdk: oraclejdk8
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- mvn -T 2 -Ptravis ${JACOCO} test
- find $HOME/.m2/repository/com/google/zxing -path "*SNAPSHOT/*" -delete
- find $HOME/.m2/repository/com/google/zxing -name "*SNAPSHOT" -type d -delete
sudo: false
