after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi
before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
language: java
sudo: false
install: mvn -Ptravis -DskipTests=true -B -V install
script:
  - mvn -Ptravis ${JACOCO} test
  - find $HOME/.m2/repository/com/google/zxing -path "*SNAPSHOT/*" -delete
  - find $HOME/.m2/repository/com/google/zxing -name "*SNAPSHOT" -type d -delete
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK, Android apps
   - jdk: oraclejdk8
     env: ANDROID_HOME=$HOME/android-sdk-linux
     before_install: if [ ! -d $HOME/android-sdk-linux/platforms ]; then curl -s https://storage.googleapis.com/zxing-build/android-sdk-linux.tar.bz2 | bunzip2 | tar xf - -C $HOME; else ls -l $HOME/android-sdk-linux; fi
   # Covers Java 9
   - jdk: oraclejdk9
cache:
  directories:
  - $HOME/.m2
  - $HOME/android-sdk-linux
git:
  depth: 10
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
